name: Bitcoin Price Prediction CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python 3.12.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.5

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Run the Bitcoin prediction code
      - name: Run Bitcoin Price Prediction
        run: |
          source venv/bin/activate
          # اجرای کد شما برای پیش‌بینی قیمت بیت‌کوین
          python bitcoin_prediction.py

      # Upload plot artifacts using the latest version of the action
      - name: Upload Bitcoin Prediction Plot
        uses: actions/upload-artifact@v3
        with:
          name: bitcoin-prediction-plot
          path: plots/
